# Generated by Django 5.2.7 on 2025-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand'), ('GHS', 'Ghanaian Cedi'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('TND', 'Tunisian Dinar')], help_text="User's preferred currency for pricing display", max_length=3, null=True),
        ),
    ]
