# Generated by Django 5.2.7 on 2025-10-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_in_stock_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand'), ('GHS', 'Ghanaian Cedi'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('TND', 'Tunisian Dinar')], max_length=3)),
                ('price_cents', models.PositiveIntegerField(help_text='Price in minor currency units (cents)')),
                ('is_override', models.BooleanField(default=True, help_text='If True, use this exact price. If False, use as multiplier for base price.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_prices', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['country_code', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand'), ('GHS', 'Ghanaian Cedi'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('TND', 'Tunisian Dinar')], max_length=3)),
                ('to_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand'), ('GHS', 'Ghanaian Cedi'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('TND', 'Tunisian Dinar')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from_currency to to_currency', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['from_currency', 'to_currency'],
            },
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'country_code', 'currency'), name='catalog_productprice_unique_product_country_currency'),
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency'), name='catalog_currencyrate_unique_from_to_currency'),
        ),
    ]
