# Generated by Django 5.2.7 on 2025-10-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_in_stock_field"),
    ]

    operations = []
