# Generated by Django 5.2.7 on 2025-10-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20251005_0125"),
        ("catalog", "0006_auto_20251005_1513"),
    ]

    operations = []
