# Generated by Django 5.2.7 on 2025-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_merge_0005_auto_20251005_0125_0006_auto_20251005_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Product thumbnail', null=True, upload_to='products/thumbnails/'),
        ),
    ]
